### ISSUE TITLE
Arm and leg have incorrect starting angles

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#334] opened 2019-08-13 20:59 UTC
Self-assigning because I'm the responsible dev for John Travoltage.  Co-assigning @jessegreenberg and @zepumph because they have recent commits in this repo.

**Comment by jessegreenberg** [comment] 2019-08-15 18:35
IT looks like the arm and leg are just not visible at all, but are somehow still draggable. My first guess is that it could be caused by 5ff43f1d8078a060f6cb0b74d36e3c963bd67fe5, Ill take a look.

**Comment by zepumph** [comment] 2019-08-20 21:14
Yeah totally my fault. Commit coming in shortly.

**Comment by zepumph** [comment] 2019-08-20 21:22
The problem was that before the playAreaNode was on top of the background, but after https://github.com/phetsims/john-travoltage/commit/5ff43f1d8078a060f6cb0b74d36e3c963bd67fe5 the playAreaNode (created and added as a child in the parent) was below the background. I fixed this by adding all children to the screenView, and then setting the accessibleOrder of the playArea/controlArea Nodes at the end of the constructor. This is more idiomatic these days anyways. @samreid please review.

**Comment by zepumph** [comment] 2019-08-20 21:23
Also tagging https://github.com/phetsims/scenery-phet/issues/381 because that is the parent issue of the conversion that caused this bug.

**Comment by samreid** [comment] 2019-08-20 23:17
@jessegreenberg would you have time to review this?

**Comment by jessegreenberg** [comment] 2019-08-22 18:57
Thanks for fixing this @zepumph, https://github.com/phetsims/john-travoltage/commit/bfaedc152974c7185fc41d02a547c0036846b769 looks good. Arm and leg look good and I inspected the a11y-view and saw that things are in the correct accessible order. Closing.

**Closed by jessegreenberg** 2019-08-22 18:57 UTC
Labels: status:blocks-sim-publication, status:ready-for-review
