### ISSUE TITLE
Sim won't open on Android app

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#443] opened 2021-07-30 22:43 UTC
For https://github.com/phetsims/qa/issues/676. Seen on Galaxy Tab A Android 8.1. In the app, when trying to open the sim, it gets to the phet logo but the loading bar never starts to fill and the sim never loads.

**Comment by jessegreenberg** [comment] 2021-08-02 15:10
Thanks @KatieWoe, it definitely should, especially after https://github.com/phetsims/john-travoltage/issues/418.

Are you able to see any errors in a console or anything like that?

**Comment by KatieWoe** [comment] 2021-08-02 15:43
I don't know how to look at the console of the app on that device.

**Comment by jessegreenberg** [comment] 2021-08-02 16:26
OK, understood. I think the problem is that the audioManager is trying to initialize speech synthesis regardless of whether it is enabled. It used to be that speech synthesis was only initialized if requested from PreferencesConfiguration (which took locale and speech synth available into account).

**Comment by jessegreenberg** [comment] 2021-08-02 16:52
@KatieWoe can you please see if this is fixed in the app in https://phet-dev.colorado.edu/html/john-travoltage/1.7.0-dev.1/phet/john-travoltage_en_phet.html?

**Comment by KatieWoe** [comment] 2021-08-02 16:55
That dev version loads up in the app

**Comment by jessegreenberg** [comment] 2021-08-02 16:59
Excellent, thanks @KatieWoe, will move to the release branch.

**Comment by jessegreenberg** [comment] 2021-08-02 18:30
Cherry pick done above.

**Comment by jessegreenberg** [comment] 2021-08-14 17:57
dependencies.json updated in the above commit, ready again for another spot check to make sure this made it to the build for release.

**Comment by KatieWoe** [comment] 2021-08-18 16:19
The app now opens. However, on both the tablet and chromebook, there is no voicing option, even if it is there in the browser on the same device.

**Comment by jessegreenberg** [comment] 2021-08-18 16:44
Thanks @KatieWoe - That is what we would expect. SpeechSynthesis is not supported in an Android WebView so it will not work in the App, though it should work in a native browser on the same devices. This change removes Voicing from the sims where SpeechSynthesis is not suppoted but ensures that the sim will still run.

Closing.

**Closed by jessegreenberg** 2021-08-18 16:44 UTC
Labels: type:bug
