### ISSUE TITLE
Sim freezes in FF after reset with large number of charges

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/john-travoltage#321] opened 2018-10-27 00:02 UTC
![firefox-john-travoltage-frozen-with-audio](https://user-images.githubusercontent.com/480878/47597095-e48b3080-d948-11e8-9c97-6670d30fe95f.PNG)

It's an endless loop of "doodle" noises, which I presume are the electron noises (sounds like a lot of them).

@jbphet I'm not sure if it's related to audio, or @zepumph if it's related to fuzzBoard.

It's frozen enough where I can't get any diagnostic information out, and I can't determine what the query parameters were. I'll probably put information ABOUT the test in the visual part of the screen from now on.

**Comment by jonathanolson** [comment] 2018-10-27 00:04
In addition to dev tools not appearing, muting the tab doesn't mute the sound. Trying to close the inspector also fails. Seems like it caused some iffy behavior in the Firefox code.

**Comment by jbphet** [comment] 2018-10-29 18:10
@jonathanolson - I noticed that this isn't assigned to anyone, and I didn't want it to fall through the cracks, so I tried to duplicate it.  I ran the sim on Firefox with the `fuzz` query parameter using the current master version and didn't have any trouble.  Is there any other followup that you'd recommend?

**Comment by jessegreenberg** [comment] 2018-10-30 14:14
I ran this with ?fuzzBoard and after about 45 seconds I encountered the message "A page is slowing down..."

I have seen it freeze while pressing the reset all button and also when pressing the global mute button.

**Comment by jessegreenberg** [comment] 2018-10-30 14:17
However, running the sim with ?fuzz also froze the sim for me in Firefox, though I didn't see any message like "This tab is slowing down your browser..."

**Comment by jessegreenberg** [comment] 2018-10-30 14:34
In Firefox, if I double tap the reset all button quickly with a mouse the sim freezes.

**Comment by jessegreenberg** [comment] 2018-10-30 14:41
https://github.com/phetsims/john-travoltage/issues/321#issuecomment-434325188

The freeze only happens when there are a number of charges on the body, maybe 20 or more?

**Comment by jessegreenberg** [comment] 2018-10-30 14:48
Stepping through, I see that things bog down in this part of the model reset.
```js
      while ( this.electrons.length > 0 ) {
        this.removeElectron( this.electrons.get( 0 ) );
      }
```

Specifically, this.removeElectron( this.electrons.get( 0 ) ); begins to take a very long time.

**Comment by jessegreenberg** [comment] 2018-10-30 15:05
Continuing to step through, it was taking a long time to update the lengthProperty of the observable array, so I searched through listeners and found that with the debugger it took a long time to call these in FF:
```js
        // set the gain based on the number of electrons, this equation was empirically determined
        chargesInBodySoundClip.setOutputLevel(
          0.01 + 0.99 * ( numElectrons / JohnTravoltageModel.MAX_ELECTRONS ) * CHARGES_SOUND_GAIN_FACTOR
        );

        // set the playback speed based on the number of electrons, equation empirically determined
        chargesInBodySoundClip.setPlaybackRate( 1 + 0.25 * ( numElectrons / JohnTravoltageModel.MAX_ELECTRONS ) );
```

Since it seems like this may be related to SoundGenerator, handing over to @jbphet.

**Comment by jessegreenberg** [comment] 2018-10-30 17:32
Renaming the issue since it isn't really related to CT.

**Comment by jbphet** [comment] 2019-03-13 17:34
I think that this problem may have been caused by a combination of two other issues that have been resolved.  The first is that if the audio context was not enabled, the tambo sound library would leak memory (see https://github.com/phetsims/friction/issues/161).  The other is that opening the dev tools in Firefox changes the state of the audio context (see https://github.com/phetsims/tambo/issues/58#issuecomment-463794239).  Both have been addressed, and I haven't been able to duplicate this issue.

In an attempt to duplicate, I tried the following:
1. Fill JT's body up with charges, then hit the "Reset All" button.  I did this ~10 times in a row and never saw any problems
2. Fuzz test for 5 minutes, seemed to run fine

I did both of the above with the dev tools closed, since the main question is whether there is a problem with the sim in a normal use case.

Assigning to QA to see whether this issue can be duplicated on either the published version or the current master version.  Only Firefox needs to be tested, but it should be checked on at least one Windows and one Mac OS device.  If the problem can't be duplicated, please close.

**Comment by KatieWoe** [comment] 2019-03-14 18:11
I did both tests on Mac 10.14 Firefox and Win 10 Firefox.  Both with and without dev tools open.  Did not see this occur.  Closing

**Closed by KatieWoe** 2019-03-14 18:11 UTC
Labels: status:blocks-sim-publication, type:bug
