### ISSUE TITLE
Issue with charge states

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/john-travoltage#254] opened 2017-05-30 14:56 UTC
While testing for https://github.com/phetsims/john-travoltage/issues/198, I noticed that charge states are incorrect in the state wrapper.  Here is an example:

![capture](https://cloud.githubusercontent.com/assets/6396244/26589608/b0582156-4515-11e7-94d1-355aaa627679.PNG)

**Comment by phet-steele** [comment] 2017-05-30 21:32
@samreid @zepumph This is something I showed @jessegreenberg on Friday, so it is for phetsims/tasks/issues/846

**Comment by zepumph** [comment] 2017-06-07 23:24
I seem to be getting the same error as I do in the About dialog issue https://github.com/phetsims/phet-io/issues/1143:

```
assert.js:21 Uncaught Error: Assertion failed: mismatched messageIndex, possible start/end mismatch
    at window.assertions.assertFunction (assert.js:21)
    at Object.end (phetioEvents.js?bust=1496877807715:154)
    at SimIFrameAPI.js?bust=1496877807715:268
```

I think that this is an error that is downstream of the cause, but the cause is breaking the phetio engine in a consistent way.

**Comment by zepumph** [comment] 2017-06-08 23:49
@samreid I would love some help on this one, let's talk tomorrow.

**Comment by zepumph** [comment] 2017-06-09 21:27
@jessegreenberg may want to review these commits.

**Comment by phet-steele** [comment] 2017-06-12 16:58
This looks good to me. Keeping open for @jessegreenberg to review.

**Comment by jessegreenberg** [comment] 2017-06-12 17:20
In https://github.com/phetsims/john-travoltage/commit/9759871a4532b9ecfa11a5ba2fd69b4aee53386e ```regionText``` wasn't being set so position of the arm is missing from the alert that happens when a discharge occurs.  Fixed in master.  @zepumph should this be cherry picked into 1.4-phetio?

**Comment by jessegreenberg** [comment] 2017-06-12 17:32
To clarify, for an alert:
> "Discharge occurred. Electrons on body decreased from 45 to 0 with hand at position -2, very close to doorknob."

"very close to doorknob" was missing.

**Comment by jessegreenberg** [comment] 2017-06-14 20:26
Thanks @zepumph looks like cherry-pick is done, can this be closed?

**Comment by zepumph** [comment] 2017-06-14 20:35
Yeah, thanks for keeping me honest, closing.

**Closed by zepumph** 2017-06-14 20:35 UTC
Labels: dev:phet-io, status:fixed-pending-testing, type:bug
