### ISSUE TITLE
Tapping the sim reads out previous interaction

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#413] opened 2021-05-11 16:41 UTC
**Test device**
iPad 6th Gen
**Operating System**
iPadOS 14.5.1
**Browser**
Safari
**Problem description**
For https://github.com/phetsims/QA/issues/645. Did not see on Win 10 Chrome with mouse or touch.
On the iPad Safari sim, if you tap the screen on a non-interactive portion, it will read out a previous interaction, such as the leg or arm swinging.
**Steps to reproduce**
1. Turn on voicing
2. Swing the leg to pick up electrons
3. Tap a non-interactive part of the screen, such as the window

**Visuals**

https://user-images.githubusercontent.com/41024075/117853145-4ed4f980-b245-11eb-9fa1-db9b415fdacb.MOV

**Comment by KatieWoe** [comment] 2021-05-11 16:49
In addition, it seems that sometimes it will read leg swing when it should read arm swing or vice versa. It often omits arm or leg swing while performing those actions entirely.

**Comment by jessegreenberg** [comment] 2021-06-10 22:22
I confirmed that this is an issue for https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.4/phet/john-travoltage_en_phet.html, but verified that this is no longer happening in master. A lot of improvements were made to the input listener since this dev version was created, mostly https://github.com/phetsims/scenery/issues/1217. I am assuming this has been resolved since then , closing this issue.

**Closed by jessegreenberg** 2021-06-10 22:22 UTC
Labels: type:a11y-bug, type:bug
