### ISSUE TITLE
Investigate re-entrant Properties

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#298] opened 2018-09-04 01:35 UTC
In https://github.com/phetsims/axon/issues/179 we identified Property instances that are re-entrant.  In this context, re-entrant means a change in value of the Property causes (via listeners) another change in the value of the same Property instance.

Re-entry can occur for at least 3 different reasons, which are document here: https://github.com/phetsims/axon/issues/179#issuecomment-414717687

```
value=0.9999999999999998, oldValue=1 // epsilon problem
value=-0.4277580409572783, oldValue=-0.5 // large delta problem
value=[Object], oldValue=[Object] // object changed to object problem.  May be same object?
```

This issue is to search through the Properties with `reentrant: true` and:

(a) confirm that the Property really requires `reentrant: true`
(b) identify the reason for the reentry (may be one of the 3 classes above)
(c-i) see if the code can be rewritten so it no longer requires a reentrant Property, or document why the code uses a re-entrant Property
or
(c-ii) document why the code uses a re-entrant Property

Initially assigning to the responsible-dev for this repo, though it is unclear what the priority should be for this issue.

**Comment by samreid** [comment] 2018-09-11 19:42
You can reproduce this problem by temporarily changing `reentrant` to `false`, then dragging the leg and pressing reset.  The stack trace goes through a DynamicProperty, which I traced to `AppendageNode`.  If you make that DynamicProperty `bidirectional: false` then the re-entry problem goes away.

**Comment by samreid** [comment] 2018-09-11 19:44
I also noticed there is a comment about this in the DynamicProperty:

```js
// only update angle if we are not mouse dragging to avoid reentrance
```

@jessegreenberg can you please look into this issue?

**Comment by jessegreenberg** [comment] 2019-04-11 22:43
A related issue recently came up in #330. I am unable to reproduce the reentrance on master when I remove `reentrant` from `angleProperty` and the relevant lines in inverseMap of DynamicProperty. I *can* however reproduce the issue when I checkout SHAS from around the date of this issue. So this may have been fixed by other commits in this repo, Ill investigate.

**Comment by jessegreenberg** [comment] 2019-04-11 22:54
I think I found it, there was an issue with AccessibleSlider identified in https://github.com/phetsims/gravity-force-lab-basics/issues/72 and the general fix made it so that this is no longer reentrant. I will remove `reentrant: true` and other references here and test to make sure reentrance is no more while everything still works.

**Comment by jessegreenberg** [comment] 2019-04-11 23:01
`reentrant: true` removed and sim is passing fuzz tests and a11y features are working. I can't reproduce the problem when going through steps in https://github.com/phetsims/john-travoltage/issues/298#issuecomment-420398958. Lines and documentation in https://github.com/phetsims/john-travoltage/issues/298#issuecomment-420399482 were removed. Closing.

**Closed by jessegreenberg** 2019-04-11 23:01 UTC
