### ISSUE TITLE
(Sound) When using Self-voicing version, I hear crackling

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#376] opened 2020-10-30 12:18 UTC
This may be related to https://github.com/phetsims/faradays-law/issues/192

I am getting a noticeable crackle when I test the Self-voicing version of John Travoltage on my iPhone 7 iOS 13.7

Not sure if anything can be done, but I thought I should make an issue.

**Comment by terracoda** [comment] 2020-10-30 12:20
Assigning to both @jessegreenberg @jbphet, so both are aware of the issue. Please, re-assign or un-assign as necessary.

**Comment by jessegreenberg** [comment] 2020-10-30 16:03
Hmm, unfortunately I am not able to reproduce this on my Windows 10 Machine with Chrome or my iPhone 8 on 13.6.1.

@terracoda are you hearing any crackling on your phone when self-voicing is disabled? Not sure if it is related to the two playing at once or if crackling is just happening in general.

**Comment by jbphet** [comment] 2021-04-21 18:36
I tried to replicate this on an iPhone 8 running iOS 14.4.2, an iPad model A2270 running iOS 14.4, and in Chrome on my main development machine, which is running Windows 10.  I ran the prototype self-voicing version that is currently linked on the main PhET website as a prototype, which is https://bayes.colorado.edu/dev/html/john-travoltage/1.6.0-dev.41/phet/john-travoltage_en_phet.html?supportsSelfVoicing.  In none of these cases did I hear any crackling.  In fact, I would say it sounded quite good in all three cases, and used different default voices, which was pretty cool.

There isn't much else I can do here, and it doesn't seem like it's worth a lot more of my time.  I'm assigning back to @terracoda to make a recommendation as to whether this is a significant enough problem that we should enlist QA to try to identify devices on which the problem can be reliably repeated.  If the recommendation is that the problem be investigated further, the issue should be assigned to QA.

**Comment by emily-phet** [comment] 2021-07-02 18:26
I heard crackling as well, when giving a demo to a teacher (using safari browser on my MacBook Pro with Big Sur). 

@jessegreenberg can you send me the latest link, and I'll see if it still occurs?

**Comment by jessegreenberg** [comment] 2021-07-13 15:32
@emily-phet sure here is the latest link:

 https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.42/phet/john-travoltage_en_phet.html

Were you using Zoom to give the demo? I know in https://github.com/phetsims/ratio-and-proportion/issues/229 we found that Zoom had some audio crackling, and could be related.

**Comment by emily-phet** [comment] 2021-07-14 20:21
@jessegreenberg Thanks for the reminder re zoom and crackling. Yes, I was using Zoom. Playing with the link above for a while, I heard no crackling. 

Unfortunate that this may happen quite readily with Zoom, but no need to slow publication for this. Presumably if there is a non-Zoom scenario that crackles, the QA team will find it. Otherwise, let's just chalk this up to a known Zoom issue, and hopefully whatever the root cause of it is can be addressed by Zoom in the future.

**Comment by emily-phet** [comment] 2021-07-14 20:22
Closing this issue now. If QA finds crackling somewhere, then we can put some further time into tracking down a problem.

**Closed by emily-phet** 2021-07-14 20:22 UTC
Labels: dev:sonification
