### ISSUE TITLE
HTML strong tags visible in Keyboard Shortcuts Dialog

### ISSUE THREAD

**Issue by terracoda** [phetsims/john-travoltage#229] opened 2017-04-17 02:23 UTC
Not sure why the code of the`<strong>` elements are visible in keyboard shortcuts dialog. Perhaps it is due to the `aria role document`? Strangely, code of other elements is not showing up.

Screen shot on Mac OSX Sierra 10.12.3 with Safari 10.0.3
<img width="780" alt="screen shot 2017-04-17 at 07 45 27" src="https://cloud.githubusercontent.com/assets/1902116/25076869/71b05698-2342-11e7-9b1a-e20e6c7147aa.png">

**Comment by terracoda** [comment] 2017-04-17 02:30
@jessegreenberg, if the `<b>` actually works, just use it instead. The same thing happens in Firefox Chrome.

**Comment by jessegreenberg** [comment] 2017-04-17 03:12
Thanks for catching @terracoda.  I would expect ```<b>``` to have this behavior now too, this is likely caused by a change to HTMLText.

**Comment by terracoda** [comment] 2017-04-17 05:12
@jessegreenberg, it would be nice to have bold/strong text for visual users, but I think if need be you can de-priortize this issue and just remove the html mark-up until it can be fixed in Scenery.

**Comment by jessegreenberg** [comment] 2017-04-17 20:38
Ok thanks @terracoda - this is only an issue in the built version so I would like to investigate.

**Comment by jessegreenberg** [comment] 2017-04-17 20:43
This is no longer an issue for requirejs or built versions - honestly no idea why:

![capture](https://cloud.githubusercontent.com/assets/6396244/25104060/241baf06-237c-11e7-9c80-d95b4d5df88b.PNG)

Closing.

**Closed by jessegreenberg** 2017-04-17 20:43 UTC
Labels: dev:a11y, type:bug
