### ISSUE TITLE
Replace the artwork

### ISSUE THREAD

**Issue by samreid** [phetsims/john-travoltage#83] opened 2015-08-06 17:49 UTC
@kathy-phet suggested replacing the artwork in John Travoltage.  @ariel-phet asked me to create an issue and assign it to him.

**Comment by ariel-phet** [comment] 2015-08-11 04:20
assigning to @samreid and will get him the artwork when https://github.com/phetsims/tasks/issues/309 is complete

**Comment by samreid** [comment] 2015-08-13 01:14
@ariel-phet I'm using my assigned issues as a live "TODO list".  I'm going to unassign this until the artwork is complete.  Please reassign this to me when https://github.com/phetsims/tasks/issues/309 is complete.

**Comment by ariel-phet** [comment] 2015-08-13 04:18
@samreid sounds good

**Comment by jessegreenberg** [comment] 2016-02-26 00:22
In #86, new face image was added and the arm appendage was gray scaled so that the whole body looked unified.

**Comment by phet-steele** [comment] 2017-02-08 17:50
In #86, the new face image was simply layered over the old. The old image still exists in the sim. Thanks to the wonders of PhET-iO, you can reveal the image by disabling the new face:

<img width="1292" alt="screen shot 2017-02-08 at 10 47 31 am" src="https://cloud.githubusercontent.com/assets/5863899/22749883/0aff5510-edec-11e6-8330-b6d8f579441a.png">

We cannot simply remove the old image since it is part of the body. We may need to add in new artwork (from https://github.com/phetsims/tasks/issues/309 ?). This is mostly a question for @kathy-phet and should be brought up at next status.

**Comment by arouinfar** [comment] 2017-02-09 17:54
I imported the updated head image into the .ai file for the body, and have created a new body asset. Here's what it looks like:

<img  width=200, src="https://cloud.githubusercontent.com/assets/8419308/22795936/b42046f8-eeb5-11e6-8fad-32542027ed0e.png">

The original assets for the body and head were both really pixellated when I opened them in Illustrator, so the alignment was a bit hard to judge. @jessegreenberg please let me know if you'd like me to further edit the new asset.

**Comment by jessegreenberg** [comment] 2017-02-09 18:16
@arouinfar discovered that the asset for the body is linked to a white background (not transparent).  So we will need to create a new asset from the old body image and the new face image.

**Comment by arouinfar** [comment] 2017-02-09 19:14
I've emailed you an updated asset @jessegreenberg.

**Comment by jessegreenberg** [comment] 2017-02-11 00:54
Here is a version with the face and body merged into the same image:
http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.0-dev.12/john-travoltage_en.html

The hair is a bit more aliased in this version, here is a comparison:

Before:
![before](https://cloud.githubusercontent.com/assets/6396244/22849279/ed3c4988-efb8-11e6-9ee2-6afb58d40209.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/6396244/22849280/f11275c8-efb8-11e6-812a-1f7e937ccb04.PNG)

@arouinfar would you mind sending me an updated .ai file?  @ariel-phet and @arouinfar any thoughts on the image quality? I am not sure how much time it is worth if the images are going to be updated eventually anway.

Could scaling the head in photoshop be reducing the reducing the quality of the image?

**Comment by arouinfar** [comment] 2017-02-13 19:09
@jessegreenberg I've emailed the latest .ai file to you. I think the problem is that the original assets for the head and body were both .png files. There should be an .ai file for the head somewhere, but I couldn't find it in Mariah's artwork folder or checked into GitHub. Perhaps @ariel-phet has a copy?

**Comment by jessegreenberg** [comment] 2017-02-13 19:28
Thanks @arouinfar, sorry about that. I checked in the asset:

https://github.com/phetsims/john-travoltage/blob/master/assets/face.ai

**Comment by arouinfar** [comment] 2017-02-13 19:30
Thanks @jessegreenberg! I can replace the head image with the .ai asset, which should reduce the aliasing around the head.

**Comment by arouinfar** [comment] 2017-02-13 19:49
@jessegreenberg I've emailed you the updated assets. I replaced the head with the .ai asset, but had to make it a slightly larger to completely hide the aliasing of the image beneath it.

**Comment by jessegreenberg** [comment] 2017-05-02 19:13
@arouinfar the image quality is much better now, thanks!
Old:
![2](https://cloud.githubusercontent.com/assets/6396244/25634725/e62042ac-2f38-11e7-91f4-2ef489396e7c.PNG)

New:
![1](https://cloud.githubusercontent.com/assets/6396244/25634728/e7198740-2f38-11e7-9003-388870a7d00c.PNG)

@arouinfar @ariel-phet the original issue was that @kathy-phet wanted to replace the artwork.  Can this be closed or is there more to do for that task?

**Comment by arouinfar** [comment] 2017-05-02 19:28
Looks great @jessegreenberg! I don't believe there's anything left to do for this issue, as we're tracking the replacement of the artwork in https://github.com/phetsims/john-travoltage/issues/121.

**Closed** 2017-05-10 16:10 UTC
Labels: design:artwork
