### ISSUE TITLE
Sim title not translatable?

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/john-travoltage#325] opened 2019-01-14 16:59 UTC
A translator notified phethelp that the sim title doesn't appear on the translate page.
I dug around a little bit... not sure if this might be the cause?
```
"john-travoltage.title": {
    "value": "John Travoltage",
    "visible": false
```

![image](https://user-images.githubusercontent.com/5090275/51127573-ff9c6c80-17e2-11e9-9342-f74c805e166e.png)

**Comment by arouinfar** [comment] 2019-01-14 18:12
@oliver-phet at first, I thought this may have been by design, as "John Travoltage" is essentially a name. However, it looks like [Java ](https://phet.colorado.edu/en/simulation/legacy/john-travoltage#translations-header)and earlier versions of the [HTML5 sim](https://phet.colorado.edu/en/simulation/travoltage#translations-header) did allow localization of the sim name.

It seems a bit odd to me that the sim name isn't localizable, so co-assigning to @samreid (responsible-dev) and @jbphet (most recently worked on this sim).

**Comment by samreid** [comment] 2019-01-14 18:22
@oliver-phet, nice detective work!  Co-assigning @jessegreenberg since he added the "visible":false part in d134f03001a3e327a399d27021d012fd052b5c84.  I'm also noticing 16 total hits of `"visible": false` across our project--we should discuss those as well.

**Comment by jessegreenberg** [comment] 2019-01-14 18:59
Very sorry, `"visible": false` should not be on this title string or any string. I verified that there is a check for this flag in `rosetta/routeHandlers`, which surprised me because I thought we verified that this was not the case and why we started using separate *A11yStrings.js files.
```js
const stringVisible = strings.hasOwnProperty( key ) && ( ( strings[ key ].visible === undefined ) ? true : strings[ key ].visible );
          if ( stringVisible ) {
            ...
```

To fix this, can we delete this flag from the title string in john-travoltage and deploy a maintenance release? @jbphet for the other usages of `visible: false` will there be any consequences in deleting the associated strings from the json files, possibly moving them to an *A11yStrings.js file?

**Comment by jbphet** [comment] 2019-01-16 17:33
> To fix this, can we delete this flag from the title string in john-travoltage and deploy a maintenance release? 

Yes, that should work.

> @jbphet for the other usages of visible: false will there be any consequences in deleting the associated strings from the json files, possibly moving them to an *A11yStrings.js file?

I'm not clear on this part.  I thought we decided to use the `visible: false` attribute to prevent a11y strings from appearing in the translation utility, and it appears that this works, but that the title for this sim got inadvertently marked as invisible.  Why would we need to move a11y strings to a separate file?

**Comment by jessegreenberg** [comment] 2019-01-16 17:47
Our convention has changed to use separate *A11y strings files and the great majority of a11y strings are separated in this way. The current 16 strings with `"visible": false` are exceptions to this. Actually, it looks like many of the a11y strings with "visible: false"in common code are not being used anymore.

**Comment by jbphet** [comment] 2019-01-16 18:12
Okay, thanks for the clarification.  As for the original question about whether it is safe to remove them, I think they would need to be examined on a case-by-case basis and, as long as they are not used in the visual portion of the sim, it should be safe to remove them from the strings JSON files.

**Comment by jessegreenberg** [comment] 2019-01-22 16:04
OK, sounds good, thanks. Ill fix john-travoltage here, then make a new issue in tasks to inspect and remove the rest of the strings with `visible: false`

**Comment by oliver-phet** [comment] 2019-01-22 17:07
This has been fixed and the translator notified.

**Comment by jessegreenberg** [comment] 2019-01-22 17:15
Thanks @oliver-phet! john-travoltage 1.5.2 was deployed, and I verified that there were no other changes by comparing the built file to 1.5.1. The rest of the work will continue in https://github.com/phetsims/tasks/issues/984. Closing.

**Closed by jessegreenberg** 2019-01-22 17:15 UTC
Labels: type:i18n, type:user-feedback
