### ISSUE TITLE
(Haptics) Decrease duration of charge pickup vibration

### ISSUE THREAD

**Issue by emily-phet** [phetsims/john-travoltage#386] opened 2020-11-02 19:52 UTC
The electron transfer onto body vibration could be slightly shorter. We want to avoid it feeling like the iOS default vibrations (e.g., the one you feel when grabbing the leg/arm), so if shortening it does that, let’s not. @jessegreenberg  – I suggest try shortening the vibration by 20% and then by 50%. See if any of these feel like the iOS default vibration (or compare the numbers, if you know the specs on that default vibration). If one or both of these feel like the iOS default vibration, scrap the whole idea. If one or both of these *do not* feel like the iOS default vibration, go with the shortest duration that *doesn’t* feel like the iOS default vibration.

**Comment by jessegreenberg** [comment] 2020-11-04 00:22
This was a duplicate of #387

**Closed by jessegreenberg** 2020-11-04 00:22 UTC
