### ISSUE TITLE
Voicing only reads out PhET Website and menu

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/john-travoltage#410] opened 2021-05-10 20:39 UTC
**Test device**
Lovelace
**Operating System**
ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/645
When opening the PhET menu. the website is the only thing read out. The voicing then reads out "PhET Menu" no matter what was selected.

**Visuals**

https://user-images.githubusercontent.com/41024075/117721622-53de6e00-b19d-11eb-9f4b-80c16e37ec1c.MOV

**Comment by jessegreenberg** [comment] 2021-06-11 18:00
This is happening because for those two menu buttons focus is moving back to the PhET Menu. This is a more general problem where Voicing will read the object that has focus, even when it is focus placed programatically with mouse/touch interaction. Sometimes this works out well, but it seems like mostly this is undesireable.

**Comment by jessegreenberg** [comment] 2021-06-22 17:50
I think this is actually OK. We don't have any alert to signify that a menu item was selected, we just read out what has focus after the menu item selection. This is not a bug but a design implication that we don't have an alert for PhET menu items. Using the PhET menu feels natural to me with voicing, but if we want to add voicing alerts in this case we can do so in the future. I think Ill close this one.

**Closed by jessegreenberg** 2021-06-22 17:50 UTC
Labels: type:a11y-bug, type:bug
