### ISSUE TITLE
Automated Testing Error

### ISSUE THREAD

**Issue by Denz1994** [phetsims/john-travoltage#202] opened 2017-03-23 14:47 UTC
Caught this error while running:

phetmarks=>aqua=>Test Sims(Fast Build) with PhET-iO checked.

```
Uncaught TypeError: scenery.AccessiblePeer is not a constructor
TypeError: scenery.AccessiblePeer is not a constructor
    at AccessibleInstance.initializeAccessibleInstance (http://localhost:8080/scenery/js/accessibility/AccessibleInstance.js?bust=1490280161437:75:21)
    at new AccessibleInstance (http://localhost:8080/scenery/js/accessibility/AccessibleInstance.js?bust=1490280161437:30:10)
    at Function.createFromPool (http://localhost:8080/scenery/js/accessibility/AccessibleInstance.js?bust=1490280161437:374:18)
    at new Display (http://localhost:8080/scenery/js/display/Display.js?bust=1490280161437:250:57)
    at new Sim (http://localhost:8080/joist/js/Sim.js?bust=1490280161437:294:20)
    at http://localhost:8080/john-travoltage/js/john-travoltage-main.js?bust=1490280161437:47:5
    at window.phetLaunchSimulation (http://localhost:8080/joist/js/SimLauncher.js?bust=1490280161437:50:11)
    at doneLoadingImages (http://localhost:8080/joist/js/SimLauncher.js?bust=1490280161437:60:18)
    at Object.launch (http://localhost:8080/joist/js/SimLauncher.js?bust=1490280161437:114:9)
    at http://localhost:8080/john-travoltage/js/john-travoltage-main.js?bust=1490280161437:46:15
```

**Comment by jessegreenberg** [comment] 2017-03-23 17:48
@Denz1994 is it possible you had a stale scenery SHA when running this test?  I can't reproduce this issue on master, and I think this might have been fixed via https://github.com/phetsims/scenery/commit/2a86608e07d62694231ea0bfd8f51dad1e1437e3 yesterday afternoon.

**Comment by Denz1994** [comment] 2017-03-23 18:50
I believe you are correct. I pulled from scenery yesterday morning and may have missed this repo this morning. I updated my repo and ran the above test several times and I could not reproduce this error. Leaving this up to @jessegreenberg to close.

**Comment by jessegreenberg** [comment] 2017-03-23 19:09
Thanks @Denz1994! Closing for now then.

**Closed by jessegreenberg** 2017-03-23 19:09 UTC
Labels: type:automated-testing
